daostack/subgraph

- src/mappings/uController/UController.graphql
- src/mappings/uController/UController.ts
- subgraph.handlebars.yaml
- test/integration/UController.spec.ts
Add TokenContract as a field in uControllerOrganization
> Ucontroller daotoken

- src/domain/index.ts
- src/domain/member.ts
- src/domain/schema.graphql
- src/mappings/NativeReputation/mapping.ts
- src/mappings/NativeReputation/schema.graphql
- src/mappings/Reputation/mapping.ts
- src/utils.ts
- test/integration/domain.spec.ts
This pr handle dao's members entity for the case there is a reputation and token minting before the dao creation. (e.g by using the daocreator) .
- Add test to verify migration pre deploy dao members.
fix: #45 .
> More members handling

- src/domain/schema.graphql
> remove proposals field from member

- package-lock.json
- package.json
- src/domain/proposal.ts
- src/domain/schema.graphql
- test/integration/domain.spec.ts
> Fixed GP params

- docker-compose.yml
- ops/mappings.json
- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- test/integration/domain.spec.ts
- test/integration/util.ts
> Refactor domain test

- src/mappings/DAOToken/mapping.ts
- src/mappings/DAOToken/schema.graphql
- test/integration/DAOToken.spec.ts
> Added allowances

- src/domain/index.ts
- src/domain/schema.graphql
- src/domain/vote.ts
> Voter as address

- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- test/integration/domain.spec.ts
> Add totalRep to proposal

- src/mappings/DAOToken/mapping.ts
- src/mappings/DAOToken/schema.graphql
- test/integration/DAOToken.spec.ts
> Fix allowances

- docker-compose.yml
- package-lock.json
- package.json
- src/domain/dao.ts
- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- src/mappings/GenesisProtocol/datasource.yaml
- src/mappings/GenesisProtocol/mapping.ts
- test/integration/DAOToken.spec.ts
- test/integration/domain.spec.ts
- test/integration/util.ts
resolve #43 
resolve #90 
resolve #109 
support ConfidenceLevelChange
update domain tests
use migration 11_v1
fix npm audit - security warnings
> add threshold to dao entity.

- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- test/integration/domain.spec.ts
resolve #107  - add preBoostedAt
resolve #108
> fix proposal confidenceThreshold

- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/reward.ts
- src/domain/schema.graphql
- src/domain/stake.ts
- src/domain/vote.ts
- src/mappings/DAOToken/mapping.ts
- src/mappings/GenesisProtocol/mapping.ts
- test/integration/GenesisProtocol.spec.ts
- test/integration/domain.spec.ts
This PR handle GenesisProtocol rewards.
This PR is not handle ContributionReward rewards.
{
proposals {
gpRewards{
id
tokensForStaker
reputationForProposer
reputationForVoter
tokenAddress
redeemedTokensForStaker
redeemedReputationForVoter
redeemedDaoBountyForStaker
redeemedReputationForProposer
beneficiary
createdAt
dao {
id
}
proposal {
id
}
}
}
}
resolve #93
> Handle Rewards

- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- test/integration/domain.spec.ts
handle ContributionReward rewards.
This pr + #116 fix #59
> link ContributionRewardProposal to Proposal 

- .gitignore
- README.md
- ops/generate-subgraph.js
- ops/graph-deploy.js
- ops/mappings.json
- ops/settings.js
- package-lock.json
- test/integration/util.ts
Support deployment to The Graph servers
> New deploy

- src/domain/index.ts
- src/domain/reward.ts
- src/domain/schema.graphql
- src/domain/stake.ts
- src/domain/vote.ts
- test/integration/domain.spec.ts
> Add DAO to vote and stake

- .env
- docker-compose.yml
- ops/mappings.json
- package-lock.json
- package.json
- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- src/mappings/ContributionReward/datasource.yaml
- src/mappings/GenericScheme/datasource.yaml
- src/mappings/GenericScheme/mapping.ts
- src/mappings/GenericScheme/schema.graphql
- test/integration/GenericScheme.spec.ts
- test/integration/domain.spec.ts
- test/integration/util.ts
Fix #122 
Fix #124 
Just to mention. I implemented it in a different way than the previous contracts were implemented to avoid the redundancy we currently have.
> Generic scheme

- .travis.yml
- docker/ipfs/Dockerfile
- package-lock.json
- src/domain/index.ts
- src/domain/reward.ts
- test/integration/domain.spec.ts
> Fix proposal expiredInQ state

- docker-compose.yml
- src/domain/proposal.ts
- test/integration/ipfs.spec.ts
> Safer ipfs call

- package-lock.json
- package.json
I've taken the liberty of removing the `rc` versions, and bump the minor semver version.
> version 0.0.2

- docker-compose.yml
- package-lock.json
- package.json
- src/mappings/GenericScheme/datasource.yaml
- test/integration/ContributionReward.spec.ts
- test/integration/GenericScheme.spec.ts
- test/integration/SchemeRegistrar.spec.ts
- test/integration/UController.spec.ts
> Update for Arc r.c-14

- package-lock.json
- package.json
from which the docker images are built
> version 0.0.6

- src/mappings/GenesisProtocol/mapping.ts
- test/integration/domain.spec.ts
> Fix executionState issue

- src/domain/dao.ts
- src/domain/index.ts
- src/mappings/GenesisProtocol/mapping.ts
- test/integration/domain.spec.ts
> Fix gpqueue

- src/domain/gpqueue.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- src/mappings/Controller/mapping.ts
- src/mappings/Controller/schema.graphql
- src/mappings/UController/datasource.yaml
- src/mappings/UController/mapping.ts
- src/mappings/UController/schema.graphql
- src/utils.ts
- test/integration/Controller.spec.ts
- test/integration/SchemeRegistrar.spec.ts
- test/integration/UController.spec.ts
- test/integration/domain.spec.ts
> Make GPQueue and Controller Scheme useful!

- docker-compose.yml
- ops/DummyMapping/datasource.yaml
- ops/DummyMapping/mapping.ts
- ops/generate-subgraph.js
- ops/graph-cli.js
- ops/graph-deploy.js
- ops/mappings.json
- package-lock.json
- package.json
- src/domain/index.ts
- src/domain/proposal.ts
- src/mappings/DAOToken/mapping.ts
- src/mappings/GenesisProtocol/mapping.ts
- src/mappings/Reputation/mapping.ts
- src/mappings/SchemeRegistrar/mapping.ts
- src/mappings/UController/mapping.ts
- test/integration/domain.spec.ts
graph-cli v 0.8.0
graph-ts v 0.6.0
Add redeemer to subgraph
> graphnode v 0.0.6

- docker-compose.yml
- package-lock.json
- package.json
- src/domain/reward.ts
> use latest graph-node 

- package-lock.json
- package.json
- src/domain/index.ts
> Fix quiet ending period

- package-lock.json
- package.json
- src/domain/gpqueue.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- test/integration/domain.spec.ts
> Fixed issues with gpqueue

- src/mappings/Avatar/mapping.ts
- src/mappings/Controller/mapping.ts
> Fix AvatarContract saving

- src/domain/gpqueue.ts
- src/domain/proposal.ts
- src/mappings/Controller/schema.graphql
- test/integration/UController.spec.ts
> Add gpQueue to controllerScheme

- src/domain/schema.graphql
> ControllerScheme@proposal can be null (cab be removed)

- test/integration/SchemeRegistrar.spec.ts
address #224 
this test confirm that the reported issue #224 does not exist.
> update schemeregistrar test

- docker-compose.yml
- package-lock.json
- package.json
- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/reward.ts
- src/mappings/ContributionReward/mapping.ts
- src/mappings/DAOToken/mapping.ts
- src/mappings/Reputation/mapping.ts
- src/utils.ts
remove utils `equals` function
> graph node 0.12.0

- daos/private/testdao.json
- ops/generate-contractsinfo.js
- package-lock.json
- src/domain/gpqueue.ts
- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- src/mappings/Controller/datasource.yaml
- src/mappings/Controller/mapping.ts
- src/mappings/Controller/schema.graphql
- src/mappings/GenericScheme/schema.graphql
- src/mappings/UController/datasource.yaml
- src/mappings/UController/mapping.ts
- test/0.0.1-rc.16/GenericScheme.spec.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/GenericScheme.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> gpparams at schemes

- ops/mappings.json
index rc.16 on Rinkeby aswell.
> index rc16 on rinkeby

- src/domain/proposal.ts
- src/domain/reward.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> set accountswithunclaimedrewards for cr only on proposal execution

- docker-compose.yml
- package-lock.json
- src/domain/reward.ts
> check if scheme is connected to the dao upon calculate its redeem values.

- docker-compose.yml
> ipfs settings 

- src/domain/proposal.ts
- src/domain/schema.graphql
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Added totalRepWhenCreated to proposal entity

- src/domain/index.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Add proposal confidence + closingAt fields 

- .travis.yml
- src/domain/reward.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Fix CR unclaimed reward issue

- documentations/Deployment.md
This is short documentation on how to locally run a Graph Node and deploy the subgraph into it.
@jellegerbrandy @shivgupt Please feel free to add to and update this as this is very basic documentation.
> Documentation for deployment

- docker-compose.yml
- package-lock.json
- package.json
> Use migraton v19-7

- docker-compose.yml
- ops/mappings.json
- package-lock.json
- package.json
> Remove GEN mappings

- .gitignore
- daos/mainnet/testdao.json
- daos/private/testdao.json
- ops/mappings.json
- src/domain/dao.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
Fixed rep holders count.
Fixed mainnet mappings issue
> Fix members count bug

- src/domain/proposal.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Update closingAt on execution

- ops/generate-contractsinfo.js
- this pr will enable adding any dao's schemes to contractInfo entity.  even if this scheme is not included at migration.json. 
- this will enable auto naming of dao's schemes.
- the scheme should be added to the <dao>.json file under a "Scheme" field .
e.g 
```
{
"name": "Inveterate Sea barnacles",
"Avatar": "0x366b3001D730E58D45895cf635D5582f8B88Abe9",
"DAOToken": "0xCc5c0EbA633E35861252d955383880C5c6485668",
"Reputation": "0xa95Fc1a5C9eB48FBc51dD4421B2d267a544c2201",
"Controller": "0x184344F2dE1c2028041144B8ecd8D23f06924Fdc",
"arcVersion": "0.0.1-rc.22",
"Schemes": {
"ReputationFromToken":"0x1234444444444444444444444444",
"AnyCustomScheme": "address"
}
}
```
fix #296
> enable adding any dao's schemes to contractInfo entity

- src/domain/gpqueue.ts
> check if params set on schemes

- src/domain/reward.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Fix rewards

- index.js
- ops/generate-contractsinfo.js
- ops/generate-daos-subgraph.js
- ops/generate-schema.js
- ops/generate-subgraph.js
- ops/graph-codegen.js
- ops/graph-deploy.js
- ops/setup-env.js
- package-lock.json
- package.json
this PR should not change any functionality, just add the possiblity to require the package and use it as a dependency (which is useful for the test_env repo) and add some parameters (i.e. tell the repo to use  a specific migraiton.json, not the one copied in the package itself)
> make subgraph usable as a package, and add some parametrization

- .travis.yml
- daos/private/testdao.json
- docker-compose.yml
- package-lock.json
- package.json
- src/mappings/Avatar/datasource.yaml
- src/mappings/ContributionReward/datasource.yaml
- src/mappings/Controller/datasource.yaml
- src/mappings/DAORegistry/datasource.yaml
- src/mappings/DAOToken/datasource.yaml
- src/mappings/GenericScheme/datasource.yaml
- src/mappings/GenesisProtocol/datasource.yaml
- src/mappings/Reputation/datasource.yaml
- src/mappings/SchemeRegistrar/datasource.yaml
- src/mappings/UController/datasource.yaml
- test/0.0.1-rc.16/Subscription.spec.ts
- test/0.0.1-rc.16/SubscriptionLoop.spec.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/Subscription.spec.ts
- test/0.0.1-rc.19/SubscriptionLoop.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
please note that this version introduce a change in the way subscription work.
see https://github.com/graphprotocol/graph-node/pull/1062 .
> Upgrade to Graph-Node v14

- daos/mainnet/betterbrooklyn.json
- daos/mainnet/bitfwd.json
- daos/mainnet/cement.json
- daos/mainnet/curadao.json
- daos/mainnet/daofund-manager.json
- daos/mainnet/daofund.json
- daos/mainnet/dorg.json
- daos/mainnet/dxdao.json
- daos/mainnet/ethberlin-dao.json
- daos/mainnet/ethfnx.json
- daos/mainnet/ethindia-dao.json
- daos/mainnet/general-store-dao.json
- daos/mainnet/genesisalpha.json
- daos/mainnet/identity.json
- daos/mainnet/illuminati-dao.json
- daos/mainnet/kyber-fund-arb.json
- daos/mainnet/kyber.json
- daos/mainnet/liberland.json
- daos/mainnet/meme.json
- daos/mainnet/polka.json
- daos/mainnet/pravduh-dao.json
- daos/mainnet/psychedelicsociety.json
- daos/rinkeby/dxdao.json
- daos/rinkeby/fastdao.json
- daos/rinkeby/genesisalpha.json
- daos/rinkeby/newdao.json
- daos/rinkeby/rep4tokendao.json
This will allow us to later make deployments through Travis build.
(Not sure if we want to merge it to master or keep it as a separate branch.)
> Add DAOs to index

- README.md
- ops/generate-daos-subgraph.js
- ops/generate-subgraph.js
Added mappings.json doc.
Added mappings.json support for non migration.json contracts.
Fix #282
> Added mappings.json doc

- docker-compose.yml
- src/mappings/Reputation/mapping.ts
- src/mappings/Reputation/schema.graphql
- test/0.0.1-rc.16/Reputation.spec.ts
> Add createAt for repHolder

- src/domain/proposal.ts
- src/domain/schema.graphql
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Add fulltext field

- daos/private/testdao.json
- docker-compose.yml
- ops/generate-contractsinfo.js
- ops/generate-daos-subgraph.js
- ops/generate-subgraph.js
- ops/mappings.json
- package-lock.json
- package.json
- src/domain/gpqueue.ts
- src/domain/index.ts
- src/domain/schema.graphql
- src/mappings/Controller/datasource.yaml
- src/mappings/Controller/mapping.ts
- src/mappings/Controller/schema.graphql
- src/mappings/GenericScheme/schema.graphql
- src/mappings/UController/datasource.yaml
- src/mappings/UController/mapping.ts
- src/mappings/UGenericScheme/datasource.yaml
- src/mappings/UGenericScheme/mapping.ts
- src/mappings/UGenericScheme/schema.graphql
- src/utils.ts
- test/0.0.1-rc.16/UGenericScheme.spec.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/UGenericScheme.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> add alias to scheme entity + none universal genericScheme support

- ops/generate-daos-subgraph.js
- src/domain/reward.ts
> use tryCall

- ops/setup-env.js
Minor fix to pass arguments to setupenv
> fix arguments parse for ops/setup-env

- daos/mainnet/blockexplode.json
- daos/mainnet/pepper4d.json
- ops/graph-deploy.js
- package-lock.json
- package.json
https://github.com/daostack/migration/blob/master/daos-params/migration-params-block-explode.json
https://github.com/daostack/migration/blob/master/daos-params/migration-params-pepper4d.json
> Add DAOs and bump version

- docker-compose.yml
- ops/generate-daos-subgraph.js
- package-lock.json
- package.json
use migration rc.24-v3
bump version
fix #331
> fix generate-daos-subgraph

- package-lock.json
- src/domain/dao.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- src/mappings/Controller/mapping.ts
- src/mappings/Controller/schema.graphql
- src/mappings/UController/mapping.ts
- test/0.0.1-rc.16/UController.spec.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/UController.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Add proposal counting per schema

- daos/mainnet/pravduh-dao.json
- ops/mappings.json
index rinkeby v24 (mapping.json)
fix #347 
fix #346
> Remove pravda dao

- src/domain/dao.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- src/mappings/Controller/mapping.ts
- src/mappings/Controller/schema.graphql
- src/mappings/UController/mapping.ts
- test/0.0.1-rc.16/UController.spec.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/UController.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Added numberOfExpiredInQueueProposals

- src/domain/proposal.ts
- src/domain/schema.graphql
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Added tags support

- ops/generate-daos-subgraph.js
- ops/generate-subgraph.js
- package-lock.json
- package.json
- src/mappings/Controller/mapping.ts
- src/mappings/Controller/schema.graphql
- src/mappings/UController/mapping.ts
fix #361 
and 
validate that data sources need to have different names
> Fix Graphnode bugs

- ops/mappings.json
> support arc rc30 in gananch

- test/sanity.spec.ts
> add sanity test

- src/domain/proposal.ts
- src/mappings/Controller/mapping.ts
- src/mappings/UController/mapping.ts
fix #371 
- init counters for schemes only if new scheme entity.
- do not decrement numberOfBoostedProposals is state change to  `QuietEndingPeriod`
> proposals counters : handle edit scheme params case

- package-lock.json
- package.json
- src/domain/proposal.ts
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> proposals counter - handle QuietEndingPeriod

- src/domain/proposal.ts
- src/domain/schema.graphql
- test/0.0.1-rc.16/domain.spec.ts
- test/0.0.1-rc.19/domain.spec.ts
> Add new tags features

- README.md
- deploy-travis.sh
- docker-compose.yml
- ops/generate-daos-subgraph.js
- ops/generate-subgraph.js
- ops/settings.js
- package-lock.json
- package.json
add start block for data sources indexing .
> graph node v 0.16

- daos/private/testdao.json
- docker-compose.yml
- ops/generate-abis.js
- package-lock.json
- package.json
use graph-cli 16.0.2 for fast upload
> Use latest migration

- daos/mainnet/genesisalpha.json
For proposal: https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0xd6111ccc5d8e8a5c0df353c35bcb19ef9851707f3a3cc04a13f963eecdff16c1
> Add Standard Bounties Generic Scheme to Genesis Alpha

- docker-compose.yml
> Update graph node to v0.16.1

- src/mappings/Competition/mapping.ts
- src/mappings/Competition/schema.graphql
- test/0.0.1-rc.36/Competition.spec.ts
> Fix reptutation typo in Competition

- ops/mappings.json
This is an accidental leftover from a small attempt I made for patching DAOTracker versioning.
> Remove mistake mappings entry

- daos/mainnet/dxdao.json
these schemes will be register soon.
see
https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x678a757914d7e3315ff753782f9c882485806a7179b2020981e7003c996d28b5
and 
https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0xb44904439fbd05c48b7d56e3ae684a5d2909cd8e8201a3cdb77442d6d33810e6
> index dxdao ens generic schemes

- daos/private/testdao38.json
- package-lock.json
- package.json
- src/mappings/Competition/mapping.ts
> Competition ties

- daos/mainnet/dxdao.json
see https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x084f14d12e448cf175d31ab6a6dd4469bfebaac47565ca93f788af16d52123ff
> Add dxdao genericscheme ens .eth dao.json

- daos/rinkeby/omentesting.json
Added Omen Testing DAO with Schemes for Rinkeby network
> Added Omen Testing DAO with Schemes

- daos/rinkeby/omentesting.json
- Updated GenericScheme addresses
> Updated GenericScheme addresses

- src/mappings/Controller/schema.graphql
> allow gp voting params to be null

- src/domain/dao.ts
- src/domain/index.ts
- src/domain/schema.graphql
- src/mappings/Avatar/datasource.yaml
- src/mappings/Avatar/mapping.ts
- src/mappings/Avatar/schema.graphql
- test/0.1.1-rc.17/Avatar.spec.ts
- test/0.1.1-rc.17/DAOFactory.spec.ts
- test/0.1.1-rc.17/util.ts
> dao metadata support

- src/domain/proposal.ts
> Fix IPFS crash

- ops/generate-contractsinfo.js
- package-lock.json
- package.json
- src/domain/schema.graphql
- src/utils.ts
- test/0.1.2-rc.0/contractsInfo.spec.ts
- test/0.1.2-rc.0/util.ts
Add UniversalContractInfo entity to keep all versions of Genesis Protocol and Redeemer.
> Add UniversalContractInfo entity

- daos/kovan/dummydao.json
- daos/mainnet/dummydao.json
- daos/rinkeby/dummydao.json
- daos/sokol/dummydao.json
- daos/xdai/dummydao.json
This is needed to make sure the subgraph is generating all the necessary abis...
> Update the dumydaos

- src/domain/dao.ts
- src/domain/proposal.ts
- src/domain/schema.graphql
- src/mappings/Controller/mapping.ts
- test/0.1.2-rc.6/DAOFactory.spec.ts
- test/0.1.2-rc.6/SchemeFactory.spec.ts
- test/0.1.2-rc.6/domain.spec.ts
> Add unregistered proposals counting

- daos/kovan/primedao.json
Hi, 
I'm want to add primedao to kovan subgraph for test purposes
Thank you
> Add primeDAO for test purposes to kovan DAOs

- daos/mainnet/primedao.json
Hi,
I want to add primedao to the mainnet subgraph
Thank you
> Add primedao mainnet setup

- package-lock.json
- package.json
- src/domain/gpqueue.ts
- src/mappings/Controller/schema.graphql
- src/utils.ts
- test/0.0.1-rc.16/SchemeRegistrar.spec.ts
- test/0.0.1-rc.19/SchemeRegistrar.spec.ts
Add error is universal scheme params were non-existent.
> Add scheme error field

- daos/mainnet/primedao.json
Hello we would like to display scheme names with spaces to enhance readability
Thank you
> Add spaces to scheme allias

- src/mappings/Controller/mapping.ts
- src/mappings/Controller/schema.graphql
- test/0.0.1-rc.55/ContinuousLocking4Reputation.spec.ts
> Index agreement hash

- package-lock.json
- package.json
- src/domain/proposal.ts
- src/mappings/GenericSchemeMultiCall/mapping.ts
- src/utils.ts
- test/0.0.1-rc.55/GenericSchemeMultiCall.spec.ts
> GSMC new closing at

- daos/mainnet/primedao.json
Add LockingToken4Reputation scheme to PrimeDAO
> Add: LockingToken4Reputation scheme
